[env:freewili]
extends = rp2350_base
board = freewili2  ; Custom RP2350B board (PICO_RP2350A=0, GPIO 0-47)
board_level = extra
upload_protocol = picotool

build_flags =
  ${rp2350_base.build_flags}
  -D FREEWILI
  -D PRIVATE_HW
  -I variants/rp2350/freewili
  -D DEBUG_RP2040_PORT=Serial
  -D __WIRE0_DEVICE=i2c1

lib_deps =
  ${rp2350_base.lib_deps}
  lovyan03/LovyanGFX@1.2.19

debug_tool = cmsis-dap
